### PR TITLE
Demo office hour todos

### PR DESCRIPTION
**Pull request by yusuferisen**
- Removed the web browser title option passed by the user, now it's using a localized but hardcoded string.
- Updated the README file as we talked
- Xcode 7.3 was released this week, and it came with Swift 3.0 updates (it didn't completely switch to Swift 3 yet, but Xcode now gives warnings for Swift 3 incompatible code to make the later transition easier)
- A couple small edits that I noticed I overlooked.

@arjand @alexclover2 

@annie-l, here's the note text I put on top of the README:
screen shot 2016-03-24 at 5 11 44 pm

### CODE REVIEW

**Comment by yusuferisen** [comment]
Tested the SDK changes within the dashboard app manually and using the UI tests.

Screenshot of the OAuth webview:

simulator screen shot mar 24 2016 5 25 00 pm

**Comment by annie-l** [comment]
thanks, the readme content and screenshot look good to me.

**Comment by arjand** [comment]
:+1:

**Comment by michael-quinlan** [comment]
@arjand  here is my reminder to remove me from this repo ;)

**Comment by arjand** [comment]
@michael-quinlan  I think you are removed. :)

**Comment by michael-quinlan** [comment]
I will never know

**Pull request merged**
